# Cloud Server Port
server.port=${PORT:8080}

# Hardcoded Cloud Database Credentials
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/hospital_system}
spring.datasource.username=${DB_USER:root}
spring.datasource.password=${DB_PASS:root}

# Hibernate Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true